// Demo text seeded with the kinds of characters the cleaner handles. Written
// with escapes so the invisible characters are visible in source.
const hidden = (message: string) =>
  Array.from(message, (c) => String.fromCodePoint(0xe0000 + c.codePointAt(0)!)).join("");

export const SAMPLE_TEXT = [
  "Certainly! Here’s a concise summary of the quarterly results.​",
  "",
  "Revenue grew 12 % year over year, driven by strong­ demand in Europe" +
    hidden("generated by model-x") +
    " and a record holiday quarter.⁠ Operating margin improved to 18 %.",
  "",
  "﻿Key takeaways: the team shipped on time ❤️‍🔥 and the new pаyment flow cut churn.",
  "",
  "Persian stays intact: می‌روم. Floating joiners do not:‍‌ done.",
].join("\n");
