"""Generate src/unicode-names.generated.ts from Python's unicodedata.

JavaScript has no equivalent of ``unicodedata.name``/``category``, which the
engine uses for stats labels ("U+200B ZERO WIDTH SPACE (Cf)"). This script
emits a table covering every code point the engine can strip or replace,
except ranges whose label is algorithmic (variation selectors 17-256,
private use, noncharacters, reserved ignorables), which are handled in TS.

Run with a recent Python so the Unicode database matches the reference:
    uv run --python 3.13 packages/core/scripts/gen-names.py
"""

from __future__ import annotations

import sys
import unicodedata
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "src" / "unicode-names.generated.ts"

# Mirrors the explicit tables in src/tables.ts (and the reference engine).
EXPLICIT = [
    0x00AD, 0x034F, 0x061C, 0x115F, 0x1160, 0x17B4, 0x17B5, 0x180B, 0x180C,
    0x180D, 0x180E, 0x180F, 0x3164, 0xFFA0, 0xFFF9, 0xFFFA, 0xFFFB,
    *range(0x200B, 0x2010), *range(0x202A, 0x202F), *range(0x2060, 0x2065),
    *range(0x2066, 0x2070), *range(0xFE00, 0xFE10), 0xFEFF,
    0x00A0, 0x1680, *range(0x2000, 0x200B), 0x202F, 0x205F, 0x3000,
    0x0410, 0x0412, 0x0415, 0x041A, 0x041C, 0x041D, 0x041E, 0x0420, 0x0421,
    0x0422, 0x0425, 0x0430, 0x0435, 0x043E, 0x0440, 0x0441, 0x0443, 0x0445,
    0x0456, *range(0xFF21, 0xFF3B), *range(0xFF41, 0xFF5B),
    *range(0xE0001, 0xE0080),
]


def main() -> None:
    cps = set(EXPLICIT)
    for cp in range(sys.maxunicode + 1):
        if unicodedata.category(chr(cp)) == "Cf":
            cps.add(cp)
    rows = []
    for cp in sorted(cps):
        ch = chr(cp)
        name = unicodedata.name(ch, "")
        if not name:
            continue  # unassigned: TS falls back to UNKNOWN (Cn)
        rows.append(f"{cp:X};{unicodedata.category(ch)};{name}")
    body = "\\n".join(rows)
    OUT.write_text(
        "// Generated by scripts/gen-names.py from Python "
        f"{sys.version.split()[0]} (Unicode {unicodedata.unidata_version}). Do not edit.\n"
        f'export const UNICODE_DATA_VERSION = "{unicodedata.unidata_version}";\n'
        "// hex code point;general category;name\n"
        f'export const NAME_TABLE = "{body}";\n'
    )
    print(f"wrote {len(rows)} names to {OUT}")


if __name__ == "__main__":
    main()
