// Bundles src/main.ts and the core engine into one dependency-free ES module
// inside the skill folder, so installing the skill is just copying that folder.
// The bundle is committed; test/bundle.test.ts fails if it is out of date.

import { build } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

export const OUTFILE = fileURLToPath(
  new URL("../../skills/remove-ai-watermarks/scripts/watermarks.mjs", import.meta.url),
);

const BANNER = `#!/usr/bin/env node
// Generated by packages/skill/build.mjs from packages/core. Do not edit by hand.
// https://github.com/heyyarun/i-hate-watermarks (MIT). Engine ported from
// https://github.com/guillaumemeyer/watermarks-remover (MIT, Copyright (c) Guillaume Meyer).`;

/** Returns the bundle's source text without writing it. */
export async function bundle() {
  const result = await build({
    entryPoints: [fileURLToPath(new URL("src/main.ts", import.meta.url))],
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node18",
    banner: { js: BANNER },
    legalComments: "none",
    write: false,
  });
  return result.outputFiles[0].text;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const code = await bundle();
  let previous = null;
  try {
    previous = readFileSync(OUTFILE, "utf8");
  } catch {}
  if (previous === code) {
    console.log(`Up to date: ${OUTFILE}`);
  } else {
    writeFileSync(OUTFILE, code, { mode: 0o755 });
    console.log(`Wrote ${OUTFILE} (${(code.length / 1024).toFixed(1)} KB)`);
  }
}
